Create ex41_Study_Practice_for_Speaking_OOP.py
Originally for line 47 I wrote:

items_total.pop[i]

which pops that index. This eventually causes the error

Traceback (most recent call last):
  File "ex41.py", line 32, in <module>
    del items_total[i]
IndexError: list assignment index out of range

because the i=key of the key:value pair != the index. Duh. Easier to shuffle, grab the last, pop the last, then to try to untangle index:key relationships. Learned a lot about how random() works, too.